all: build run clean
Num_7.o: App.cpp Files.cpp MainStructures.cpp Menu.cpp Files.h MainStructures.h Menu.h
	gcc -c -o Num_7.o App.cpp Files.cpp MainStructures.cpp Menu.cpp Files.h MainStructures.h Menu.h

build:  Num7.o
	gcc -o Num_7 Num_7.o

run: 
	Num_7.exe

clean:

	del *.o Num_7